### ISSUE TITLE
Sandor suggestion in section 2.2

### ISSUE THREAD

**Issue by karenlmasters** [tingard/gz-builder-method-paper#16]
What's the plan? I think a table might be a good idea, or putting more words on each bullet.... 

[[Sandor suggests replacing this list with a table with selection name (i.e. ”low z“), expression (0.02 < z < 0.055), number of galaxies remaining]]

**Comment by tingard** [comment]
Unfortunately I don't have the numbers for each galaxy, and it'd be a lot of work to fully replicate his mass cutoffs (I worked from the sample catalogue he provided to me)
I think adding a comment, then the mathematical notation as the second column is a good idea

**Comment by tingard** [comment]
example table:
<img width="639" alt="Screenshot 2019-09-19 at 13 12 02" src="https://user-images.githubusercontent.com/11770176/65242901-1ff19900-dadf-11e9-97f0-f2435fc143d4.png">
