### ISSUE TITLE
Median residual (as well as the median max residual)

### ISSUE THREAD

**Issue by karenlmasters** [tingard/gz-builder-method-paper#25]
Can you quote the median residual of the models as well as the median max? I know it includes sky noise, but it is a useful calibration the typical error.

**Comment by karenlmasters** [comment]
Is it possible to quote the median error on the different fit parameters for the 296 models (perhaps a table in the Result section...?)

**Comment by karenlmasters** [comment]
Where you bring in rate, comment that this was the rate of classfication on the site when needed 30 models per galaxy to aggregate. We should maybe add a line about how we felt we needed 30 to get a reliable aggregation, and tests with 15 (or was it 10) showed that wasn't enough.

**Comment by tingard** [comment]
I'm still not sure about the use of median residual - I don't know what message it's trying to tell? Sorry if I'm missing something obvious.

KDE of the median of each galaxy image, vs the median of each residual:
![download (1)](https://user-images.githubusercontent.com/11770176/65503077-18096e80-debc-11e9-982a-5e81c165553a.jpeg)

**Comment by tingard** [comment]
I find the change in maximum value and the relative amount of light subtracted much easier to conceptualise...
