### ISSUE TITLE
Abastact

### ISSUE THREAD

**Issue by CKrawczyk** [tingard/gz-builder-method-paper#30]
"These results will be used in future work to investigate spiral arm formation mechanisms and we release our catalogue of models to the community."  Does this mean the catalog is released in this paper or a as future work?

**Comment by tingard** [comment]
The plan was to release the catalog with the paper, and that we will be further using the data to analyse spiral arms

**Comment by tingard** [comment]
I see how that's confusing phrasing though...

**Comment by tingard** [comment]
How about just  "We release our catalogue of models to the community."?

**Comment by CKrawczyk** [comment]
I think that is better for the abstract.

**Comment by tingard** [comment]
Resolved in 14da0c44ff5b56b44965c765c1b6aa13c3cd7ca5
