### ISSUE TITLE
Section 2.7 question

### ISSUE THREAD

**Issue by CKrawczyk** [tingard/gz-builder-method-paper#34]
"Effective radii generally had relative errors of around 15% and axis ratios show an error of around 0.1."  Is there a missing "%" at the end of the sentence?  If not it is confusing to mix a percent with a non-percent in the same sentence.

**Comment by tingard** [comment]
the errors on axis ratio are absolute errors, while those on other parameters are relative, percentage was used to hopefully help distinguish the two but I'll try and make that more clear!
