### ISSUE TITLE
Appendix A

### ISSUE THREAD

**Issue by CKrawczyk** [tingard/gz-builder-method-paper#36]
This section could use a figure to show what this distance looks like. It is difficult to picture what these equations mean.

**Comment by tingard** [comment]
![download](https://user-images.githubusercontent.com/11770176/65439651-703e6300-de1f-11e9-8fc0-0cf9ab5ed1cd.jpeg)

Would something like this be useful as an example for one point?

**Comment by CKrawczyk** [comment]
Add some labels to the various lines and that would help a lot.

**Comment by tingard** [comment]
fixed in bd2d72957ea637575700fac290e031384ce1dee7
