### ISSUE TITLE
Typos (list of minor typos)

### ISSUE THREAD

**Issue by karenlmasters** [tingard/gz-builder-method-paper#39]
LCDM seems to be bolded in intro.

**Comment by karenlmasters** [comment]
"Compoinding"

**Comment by tingard** [comment]
> LCDM seems to be bolded in intro.

This seemed to be the best way to write LambdaCDM ($\Lambda\mathrm{CDM}$), but will change if you think it's best to do it a different way!

**Comment by karenlmasters** [comment]
"lowest redshif " missing t

**Comment by karenlmasters** [comment]
> > LCDM seems to be bolded in intro.
> 
> This seemed to be the best way to write LambdaCDM ($\Lambda\mathrm{CDM}$), but will change if you think it's best to do it a different way!

I don't know why it bolds it, but if that's all it is leave it.
