### ISSUE TITLE
References I suggest adding

### ISSUE THREAD

**Issue by karenlmasters** [tingard/gz-builder-method-paper#40]
Think we need more than just Hopkins et al. 2010 on N-bodies. Maybe look in that paper for what they cite as some of the seminal papers to include here too.

**Comment by karenlmasters** [comment]
(as a general rule, if citing an area of research I recommend to include 2-3 references from a range of dates if possible).

**Comment by karenlmasters** [comment]
"for instance a S ́ersic bulge swapping places with an exponential disc component." - could we cite Sandor on this - does he discuss this in his paper? We know he has this issue.

**Comment by tingard** [comment]
> "for instance a S ́ersic bulge swapping places with an exponential disc component." - could we cite Sandor on this - does he discuss this in his paper? We know he has this issue.

@karenlmasters Sandor simply states 
_"as in GalfitM the three components can interchange, we identified the disc has being the component with the largest effective radius, the bar being the elongated component and the bulge the component with the smallest effective radius"_

I've added him as a citation as I think this comes close enough?
