### ISSUE TITLE
Section 2.5.2 explain what `eps` and `min_points` mean

### ISSUE THREAD

**Issue by CKrawczyk** [tingard/gz-builder-method-paper#6]
You might want to include a sentence or two explaining what the `eps` and `min_points` parameters mean.

**Comment by CKrawczyk** [comment]
And also include what values you ended up using.

**Comment by tingard** [comment]
Would this not be covered by the reference to the DBSCAN paper I included? Absolutely agree the clustering parameters should be available, but should I just point people to the [gzbuilder_analysis](github.com/tingard/gzbuilder_analysis) repo?

**Comment by CKrawczyk** [comment]
I think a simple two sentence explanation along the lines of "In DBSCAN the core of a cluster is defined as a group of at least `min_points` that are all within a distance `eps` of each other.  Additionally, any points with a distance `eps` of a cluster's core are also associated with the cluster."

**Comment by tingard** [comment]
Added in 7b291ef397383c43618cbcb47db48183264ce95d
