### ISSUE TITLE
Conclusions

### ISSUE THREAD

**Issue by karenlmasters** [tingard/gz-builder-method-paper#63]
Suggest tweaks to: 
"The use of a small sample of synthetic images to calibrate and test our model clustering and fitting code has demonstrated our ability to recover galaxy morphology, despite a systematic tendancy to incorporate more bulges and fewer bars than necessary for the photometric model. As most spiral galaxies contain some form of bulge these Type 1 errors are excusable, however future work should implement an improved clustering algorithm (and improved user interface) to address the bar clustering failures present in this work. Our fitting method is still subject to the limitations of gradient-descent based optimization, for parameters for which clustering provides no prior information (bulge and bar S ́ersic n, bar boxyness)."

"The use of a small sample of synthetic images to calibrate and test our model clustering and fitting code has demonstrated our ability to recover galaxy morphology in the majority of cases. For example, our spiral arm fitting recovered spiral pitch angles to within 9 deg. This set of 9 synthetic images revealed a systematic tendency for volunteers to incorporate more bulges and fewer bars than necessary for photometric models of strongly barred spirals. Future work might  implement an improved clustering algorithm (and improved user interface) to address the failures of bar model clustering we observed in a small fraction of galaxies. "

**Comment by karenlmasters** [comment]
I don't really understand what you mean by this still: "Our fitting method is still subject to the limitations of gradient-descent based optimization, for parameters for which clustering provides no prior information (bulge and bar S ́ersic n, bar boxyness)."

**Comment by karenlmasters** [comment]
What's a "Hessian approximations"?

**Comment by karenlmasters** [comment]
Is the rate mentioned below peak, or average over a period of time? I added a "Still" to the below. 

"We were able to obtain aggregate models for 296 images with a rate of one galaxy per day, and fit photometric models for 294 images. User experience and task simplification will need to be considered if significantly larger numbers of these models are to be obtained. At the time of writing and to the best of our knowledge, the number of photometric models obtained here is still significantly larger than the largest sample obtained through purely computational photometric fitting of disc, bulge, bar and spiral arms in galaxies (10 galaxies, Gao & Ho 2017, who also included rings, disc-breaks and further components)."

**Comment by karenlmasters** [comment]
I like the ending paragraphs. Probably could start the conclusions with the current final paragraph, and end with the penultimate one.

**Comment by tingard** [comment]
> What's a "Hessian approximations"?

The [Hessian matrix of the Likelihood function is the inverse of the correlation matrix](https://onlinelibrary.wiley.com/doi/pdf/10.1002/9780470824566.app1), if your model is perfect and your parameters are Gaussian random variables.

_Edit: I've changed this from talking about Hessians to simply saying "approximations using the local curvature of the Likelihood-space", which is what Galfit does_

**Comment by tingard** [comment]
> I don't really understand what you mean by this still: "Our fitting method is still subject to the limitations of gradient-descent based optimization, for parameters for which clustering provides no prior information (bulge and bar S ́ersic n, bar boxyness)."

I mean that we are still only using gradient descent, meaning that we'll get stuck in local minima and don't obtain any true measure of uncertainty in parameters. This is most impactful for parameters like Sersic index and boxyness, for which we do not have a reliable starting point.

**Comment by tingard** [comment]
> Is the rate mentioned below peak, or average over a period of time? I added a "Still" to the below.

It's an average over time, at the peak of data collection for this sample we were receiving over 300 classifications per day (the maximum we ever received in a day is ~450)
